### ISSUE TITLE
Catching up with Ruby on Rails

### ISSUE THREAD

**Issue by amutzaba** [cdierdorff/quiz#15]
Greg has a two month head start on learning how to code using Ruby on Rails, and Greg knows exactly how this app is set up. For everyone that isn't Greg, the first week or so of this project should just be looking at the application's code, the sources where I found code, and asking Greg any questions you have about the application. This way we can all be on the same page, and work better as a team

**Comment by cdierdorff** [comment]
Greg has a two month head start on learning how to code using Ruby on Rails, and Greg knows exactly how this app is set up. For everyone that isn't Greg, the first week or so of this project should just be looking at the application's code, the sources where I found code, and asking Greg any questions you have about the application. This way we can all be on the same page, and work better as a team

**Comment by cdierdorff** [comment]
I am completed through chapter 5 of the tutorial and have a good understanding of the layout of our app compared with the first few weeks of the project.

**Comment by cdierdorff** [comment]
The group has completed this milestone.

**Comment by cdierdorff** [comment]
All assignees are complete the tutorial
