### ISSUE TITLE
The relationships from answers to questions to quizzes and scores is incorrectly modeled

### ISSUE THREAD

**Issue by cdierdorff** [cdierdorff/quiz#17]
Currently users feed of quizzes is throwing a null reference into pathing variables which is causing a pathing error on each quiz

**Comment by cdierdorff** [comment]
I updated the scores controller and am currently dealing with github branches and trying to ensure my work does not affect the master while running the app in heroku. for the mean time, i am running using rails server on localhost:3000, the default for rails.

**Comment by cdierdorff** [comment]
added a relation in the quiz and user models for scores. The scores now belong to quizzes and are indexed to quizzes and users.

**Comment by K31THSTONE** [comment]
Questions, Answers, and Quizzes now relate no matter how many questions the quiz has, or answers a question has

**Comment by amutzaba** [comment]
Relations are properly done, score is still pending to be implemented but is in place.
