### ISSUE TITLE
Database management

### ISSUE THREAD

**Issue by cdierdorff** [cdierdorff/quiz#4]
A working database that can be easily modified with rails commands. This database will have users as the primary key with quizzes, scores, and connections to other users stored with the user. 
The quizzes are attached to a specific user and can be made public or private for other users.
Each quiz contains 1 or more questions and the questions contain 1 or more answers, one of which is marked as correct by the creator.

**Comment by blongen1** [comment]
Everything in the database is linked together nicely, and scores table is correctly working as well
